# Generated by Django 5.0.7 on 2024-08-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='question',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_title',
            new_name='recipe_name',
        ),
    ]
