# Generated by Django 5.0.7 on 2024-08-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_name_ingredient_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(choices=[('mg', 'milligrams'), ('g', 'grams'), ('kg', 'kilograms'), ('mL', 'milliliter'), ('L', 'liters'), ('cup', 'cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon')], default='grams', max_length=4),
        ),
    ]
