# Generated by Django 5.0.7 on 2024-08-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(choices=[('mg', 'milligram'), ('g', 'gram'), ('kg', 'kilogram'), ('mL', 'milliliter'), ('L', 'liter'), ('cup', 'cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon')], default='gram', max_length=4),
        ),
    ]
